// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId";

/**
 * One catalogue row, as something a workspace could be given.
 */
export type ActionOffer = { 
/**
 * The catalogue identity. What is sent back to add or remove it.
 */
id: ActionId, 
/**
 * What to call it.
 */
label: string, 
/**
 * What it will do, in a sentence.
 */
describes: string, 
/**
 * The icon beside the label. Never instead of it.
 */
icon: string, 
/**
 * Whether this workspace already has it.
 */
chosen: boolean, };
