// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one of a workspace's actions stands.
 */
export type ActionState = { "kind": "ready", 
/**
 * What it will reach, when that is worth naming: the application, the
 * service. Shown so the button is never a surprise.
 */
detail: string | null, } | { "kind": "unavailable", 
/**
 * Why, in words.
 */
reason: string, } | { "kind": "unknown" };
