// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a workspace names one action.
 *
 * The same shape as an application's catalogue id: lowercase ASCII, digits and
 * hyphens, one to thirty-two bytes. Validated where it deserialises, so a slash,
 * a space, a quote, a semicolon, a newline or a null cannot be inside one —
 * which means a stored action id cannot be a path, a program or anything with
 * syntax in it, whatever else goes wrong.
 *
 * Validation is only half of it, and the smaller half. `open-editor` is a
 * perfectly well-formed id and so is `rm-rf`; the difference is that one names a
 * row in [`CATALOGUE`] and the other names nothing at all. [`find`] is the only
 * way an id becomes anything.
 */
export type ActionId = string;
