// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The identity of one application in Mira's catalogue.
 *
 * **Not a path, not a program name, not a command.** It is a slug naming a row
 * in a table compiled into the binary — `vscode`, `iterm`, `ghostty` — and the
 * only thing it can be turned into is that row. A caller who invents one gets a
 * refusal rather than a launch, because there is nothing for an unknown id to
 * resolve to ([ADR-0019](../../../docs/adr/0019-application-preferences.md)).
 *
 * Validated as it deserialises, like a commit id: lower-case ASCII letters,
 * digits and hyphens, one to [`LONGEST_APP_ID`] of them. That is defence in
 * depth — the catalogue lookup is the real wall — but a type that cannot hold a
 * path is a type nobody has to check for one.
 */
export type AppId = string;
