// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A kind of application a workspace works with.
 *
 * A *kind*, not an application. "This workspace uses an editor" is something the
 * user stated and Mira stores; "the editor here is VS Code" is something Mira
 * discovers on the machine it is running on. Keeping them apart is what lets a
 * workspace move between machines and still be true — and what lets Mira say
 * "Editor · not installed" instead of quietly forgetting the association.
 */
export type AppKind = "editor" | "terminal" | "browser";
