// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppId } from "./AppId";

/**
 * One row of the catalogue, as the interface sees it.
 *
 * Everything needed to offer a choice and to be honest about it: what it is
 * called, whether it is here, and whether Mira could actually open something
 * with it. A row that is installed and not openable is a real state — Neovim is
 * an editor and starting it from a windowed application produces a process
 * nobody can see — and saying so is better than hiding the row and letting
 * somebody wonder where their editor went.
 */
export type AppOption = { 
/**
 * How this row is named when it is chosen.
 */
id: AppId, 
/**
 * What to call it.
 */
name: string, 
/**
 * Whether this machine has it, right now.
 */
installed: boolean, 
/**
 * Whether Mira could open something with it if it were chosen.
 */
openable: boolean, };
