// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppId } from "./AppId";
import type { AppKind } from "./AppKind";

/**
 * Which application a workspace uses for one kind.
 *
 * Stored per workspace, so choosing Zed here leaves every other workspace on
 * whatever it was using. Absent means *automatic*: Mira takes the first entry in
 * its own list that this machine has, which is what every workspace did before
 * anybody chose anything.
 */
export type AppPreference = { 
/**
 * Which kind the choice is for.
 */
kind: AppKind, 
/**
 * The catalogue row chosen.
 */
application: AppId, };
