// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an application of some kind is here, and which one.
 */
export type AppPresence = { "state": "available", 
/**
 * What it is called.
 */
name: string, } | { "state": "notInstalled" };
