// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppKind } from "./AppKind";
import type { AppPresence } from "./AppPresence";

/**
 * One kind of application, and whether this machine has one.
 */
export type AppReport = { 
/**
 * Which kind was asked about.
 */
kind: AppKind, 
/**
 * What was found.
 */
presence: AppPresence, };
