// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageBoundary } from "./PackageBoundary";
import type { ProjectId } from "./ProjectId";
import type { Unattributed } from "./Unattributed";

/**
 * Where a service belongs.
 */
export type Attribution = { "kind": "project", 
/**
 * Which project.
 */
projectId: ProjectId, 
/**
 * The innermost package it is running in, when it is running in one.
 */
package: PackageBoundary | null, } | { "kind": "unattributed", 
/**
 * What stopped Mira placing it.
 */
reason: Unattributed, };
