// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Term } from "./Term";

/**
 * One author, and how often they appear in what was examined.
 */
export type AuthorCount = { 
/**
 * The name as recorded in the commits.
 */
name: Term, 
/**
 * How many of the examined commits they wrote.
 */
commits: number, };
