// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a capability works here, and if not, what to say about it.
 *
 * Every `reason` and `detail` string is **user-facing copy**, written to be read by
 * a person rather than parsed from a log. A capability that is `Unavailable` renders
 * as off *with its reason*; it is never hidden and never shown as broken
 * (`docs/architecture/platform-abstraction.md` §2).
 */
export type CapabilityStatus = { "state": "full" } | { "state": "degraded", 
/**
 * One line, shown next to the control.
 */
reason: string, 
/**
 * The longer explanation, shown on disclosure.
 */
detail: string, } | { "state": "unavailable", 
/**
 * Why not — true, specific, and not an apology.
 */
reason: string, 
/**
 * What to do instead, when there is something.
 */
fallback: string | null, };
