// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something Mira might be able to do, which some platforms cannot.
 *
 * The list mirrors the capability matrix in
 * `docs/architecture/platform-abstraction.md` §5. That matrix is the checklist:
 * a capability without a row is a capability nobody has been honest about.
 */
export type Capability = "globalShortcut" | "trayIcon" | "trayClickEvents" | "launchApplication" | "processEnumeration" | "processWorkingDirectory" | "processTermination" | "portEnumeration" | "portAttribution" | "lockDetection" | "sleepDetection" | "mediaNowPlaying" | "mediaControl" | "notifications" | "fileWatching" | "revealInFileManager" | "dragOutFiles" | "autoStart" | "batteryInfo" | "autoUpdate" | "clipboard" | "keepAwake";
