// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { CapabilityStatus } from "./CapabilityStatus";

/**
 * One capability paired with its resolved status.
 */
export type CapabilityReport = { 
/**
 * Which capability.
 */
capability: Capability, 
/**
 * Its label, so the UI does not maintain a second copy of the vocabulary.
 */
label: string, 
/**
 * How it resolved on this machine.
 */
status: CapabilityStatus, };
