// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppKind } from "./AppKind";
import type { AppOption } from "./AppOption";

/**
 * Every application Mira knows to look for, for one kind.
 */
export type Catalogue = { 
/**
 * Which kind these are.
 */
kind: AppKind, 
/**
 * The rows, in the order Mira would try them.
 */
options: Array<AppOption>, 
/**
 * What automatic picks here today, if anything.
 *
 * Shown beside the automatic choice so it is a description rather than a
 * mystery — "Automatic · Ghostty" tells you what pressing the button does.
 */
automatic: string | null, };
