// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comparison } from "./Comparison";
import type { FileChange } from "./FileChange";
import type { FilesTruncated } from "./FilesTruncated";

/**
 * The changed paths of one commit, or of the working tree.
 */
export type ChangedFiles = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "unknown" } | { "state": "ready", 
/**
 * The paths, in Git's own order.
 */
files: Array<FileChange>, 
/**
 * What they were compared against.
 */
against: Comparison, 
/**
 * Whether the list stops short, and where.
 */
truncated: FilesTruncated, };
