// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppId } from "./AppId";

/**
 * What a workspace's choice for one kind resolves to on this machine.
 *
 * Five shapes because there are five different sentences, and collapsing any
 * two of them would be a lie about somebody's machine. In particular
 * [`ChosenApp::Missing`] is **not** a reason to open something else: quietly
 * starting a different editor than the one that was chosen is the
 * unrelated-application substitution ADR-0013 refused, and a choice makes it
 * worse rather than better (ADR-0019).
 */
export type ChosenApp = { "state": "automatic", 
/**
 * What that is today, or `None` when nothing here fits.
 */
application: string | null, } | { "state": "ready", 
/**
 * The catalogue row.
 */
id: AppId, 
/**
 * What to call it.
 */
name: string, } | { "state": "missing", 
/**
 * The catalogue row, kept so the choice survives the application coming back.
 */
id: AppId, 
/**
 * What to call it.
 */
name: string, } | { "state": "notOpenable", 
/**
 * The catalogue row.
 */
id: AppId, 
/**
 * What to call it.
 */
name: string, } | { "state": "unknown", 
/**
 * What was stored, so the interface can say which one it was.
 */
id: AppId, };
