// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A commit id, in the form the interface is allowed to name one.
 *
 * A newtype with a validating conversion rather than a `String`, because this is
 * the one Git value that crosses the IPC boundary *inbound*. Anything that is not
 * hexadecimal and of a plausible length fails to deserialise, so a command taking
 * one of these can never be handed a path, a flag, or a refspec — the shapes an
 * attacker would try if Mira ran `git` (it does not; see ADR-0009).
 *
 * Abbreviations are allowed, from four characters up, because that is what a
 * person copies and what Mira itself shows.
 */
export type CommitId = string;
