// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";

/**
 * One commit, in the detail its own view shows.
 *
 * No diff. Slice 5a shows what a commit *is*; what it *changed* is 5b's read-only
 * diff view, and building half of one here would be the speculative structure the
 * roadmap's rule 8 exists to prevent.
 */
export type CommitDetail = { 
/**
 * Everything the history row already showed.
 */
commit: Commit, 
/**
 * The rest of the message, when there is more than a subject line.
 */
body: string | null, 
/**
 * The author's email as recorded in the commit.
 */
authorEmail: string, 
/**
 * How many parents it has. Two or more is a merge.
 */
parents: number, 
/**
 * How many paths it changed against its first parent.
 *
 * `None` for a merge, and honestly so: a merge's changed-file count depends
 * on which parent you compare against, so there is no single true number to
 * show. It is also `None` if the comparison could not be made.
 */
changedFiles: number | null, };
