// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { GraphRow } from "./GraphRow";
import type { Head } from "./Head";

/**
 * One page of a repository's history, with the shape of it.
 *
 * The same three-state shape as [`crate::CommitPage`], because it answers the
 * same question with more detail: "not a repository" and "cannot be read" are
 * answers the interface renders, not failures a caller has to translate.
 */
export type CommitGraph = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "ready", 
/**
 * Which branch, or which commit, this page is being read from.
 */
head: Head, 
/**
 * The commits on this page, newest first, in the same order the history
 * list uses — so the graph sits beside it row for row.
 */
rows: Array<GraphRow>, 
/**
 * Where to continue from, or `None` at the end of what is here.
 */
next: CommitId | null, 
/**
 * Whether this is a shallow clone, so the oldest row is where the
 * *copy* stops rather than where the history does.
 */
shallow: boolean, 
/**
 * How many lanes this page uses, after any collapse.
 */
lanes: number, 
/**
 * Whether the page needed more than [`MAX_LANES`] and was folded.
 */
collapsed: boolean, 
/**
 * Whether there were more references than [`MAX_REFS`] to look at, so a
 * label may be missing from a row that has one.
 */
refsTruncated: boolean, };
