// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitDetail } from "./CommitDetail";

/**
 * What Mira found when asked for one commit.
 */
export type CommitLookup = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "unknown" } | { "state": "ready", 
/**
 * What it says about itself.
 */
commit: CommitDetail, };
