// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";
import type { CommitId } from "./CommitId";
import type { Head } from "./Head";

/**
 * One page of a repository's history.
 *
 * The same three-state shape as [`crate::GitOverview`]: "not a repository" and
 * "cannot be read" are answers the interface renders, not failures a caller has
 * to translate (`prd.md` FR-3.6).
 */
export type CommitPage = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "ready", 
/**
 * Which branch, or which commit, this history is being read from.
 */
head: Head, 
/**
 * The commits on this page, newest first.
 */
commits: Array<Commit>, 
/**
 * Where to continue from, or `None` at the end of what is here.
 */
next: CommitId | null, 
/**
 * Whether this is a shallow clone, so "the end" is the end of the
 * *copy* rather than the end of the history.
 */
shallow: boolean, };
