// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One commit, reduced to what the header shows.
 */
export type Commit = { 
/**
 * The full commit id, for copying.
 */
sha: string, 
/**
 * The abbreviated commit id, for showing.
 */
shortSha: string, 
/**
 * The first line of the message.
 */
subject: string, 
/**
 * The author's name as recorded in the commit.
 */
author: string, 
/**
 * When it was authored, Unix epoch seconds UTC.
 */
committedAt: number, };
