// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a change set was compared against.
 *
 * Said out loud, because for a merge the answer would be different against the
 * other parent and a diff that did not say so would be quietly picking a side.
 */
export type Comparison = { "kind": "emptyTree" } | { "kind": "parent" } | { "kind": "firstParent", 
/**
 * How many parents it has, so the interface can say which was chosen.
 */
parents: number, } | { "kind": "head" };
