// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";

/**
 * Which set of changes is being asked for.
 *
 * Two shapes, because there are two questions: *what did this commit change* and
 * *what have I changed since*. They are kept apart deliberately — a working tree
 * is not a commit, and showing them in one list would make it impossible to tell
 * what is recorded from what is merely on disk.
 */
export type DiffScope = { "kind": "commit", 
/**
 * Which commit. Validated as it deserialises, like everywhere else.
 */
commit: CommitId, } | { "kind": "workingTree" };
