// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineKind } from "./LineKind";

/**
 * One line of a patch, with the numbers that let it be read.
 */
export type DiffLine = { 
/**
 * Added, removed, context, or a note.
 */
kind: LineKind, 
/**
 * The line number on the old side, where there is one.
 */
oldLine: number | null, 
/**
 * The line number on the new side, where there is one.
 */
newLine: number | null, 
/**
 * The text, without its trailing newline.
 *
 * Decoded lossily, because a file is bytes and a Latin-1 one must render
 * rather than panic. A line longer than [`MAX_LINE_BYTES`] is cut, and
 * `cut` says so.
 */
text: string, 
/**
 * Whether this line was cut at [`MAX_LINE_BYTES`].
 */
cut: boolean, };
