// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeKind } from "./EdgeKind";

/**
 * One line from a commit to a parent.
 */
export type Edge = { 
/**
 * The lane the parent occupies.
 */
to: number, 
/**
 * What the line means.
 */
kind: EdgeKind, };
