// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a line leaving a commit means.
 */
export type EdgeKind = "straight" | "join" | "merge" | "reordered";
