// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppKind } from "./AppKind";

/**
 * What performing an action does.
 *
 * **This enum is the whole privilege surface of the feature**, and it is
 * deliberately short enough to read in one go. Every variant is an existing
 * typed seam that already had a button somewhere in Mira; none of them takes a
 * parameter that the interface supplies, and none of them writes to a
 * repository, deletes anything, signals a process, or runs a program.
 *
 * The absences are the design and a guard test enumerates them: there is no
 * `Run`, no `Stop`, no `Kill`, no `Script`, no `Shell`, no `Exec`. Adding one
 * would be a decision with its own ADR and its own confirmation flow, not a
 * variant somebody slipped in — which is why the variant list is asserted
 * exactly rather than merely scanned for bad words.
 */
export type Effect = { "does": "openIn", 
/**
 * Editor, terminal or browser.
 */
kind: AppKind, } | { "does": "revealProject" } | { "does": "openService" } | { "does": "markOpened" } | { "does": "observe" };
