// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { FileSubject } from "./FileSubject";

/**
 * Where to continue a trace, and under what name.
 */
export type FileCursor = { 
/**
 * The file, as of the commit the walk stopped at.
 */
subject: FileSubject, 
/**
 * The commit to resume examining at.
 */
from: CommitId, };
