// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffScope } from "./DiffScope";

/**
 * Which file, said without ever naming a path.
 *
 * A change set Mira produced, a position in it, and which side of that change to
 * take the name from. The interface receives one of these and hands it back; it
 * has no way to construct a different one, and no way to describe a file Mira has
 * not already offered it.
 */
export type FileSubject = { 
/**
 * The change set the file was chosen from.
 */
scope: DiffScope, 
/**
 * Its position in that change set.
 */
at: number, 
/**
 * Take the name the file had **before** this change rather than after.
 *
 * Set when a page ends on a rename, so the next page continues under the old
 * name — which is how rename following survives pagination without a path
 * ever being sent.
 */
before: boolean, };
