// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a change list left out, if anything.
 */
export type FilesTruncated = { "state": "no" } | { "state": "yes", 
/**
 * How many are in the list.
 */
shown: number, 
/**
 * How many changed altogether.
 */
total: number, 
/**
 * The ceiling that bit ([`MAX_FILES`]).
 */
limit: number, };
