// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";

/**
 * One changed path.
 */
export type FileChange = { 
/**
 * Where this change sits in the change set.
 *
 * **This is how a file is asked for.** The interface names an ordinal in a
 * list Mira produced, never a path of its own — so there is no argument
 * through which a page could ask Mira to read a file it did not already
 * decide to offer (`security-and-privacy.md` §5).
 */
at: number, 
/**
 * What happened to it.
 */
kind: ChangeKind, 
/**
 * The path, relative to the repository root, with `/` separators.
 */
path: string, 
/**
 * Where it came from, for a rename or a copy.
 */
fromPath: string | null, 
/**
 * Whether Git considers it binary. Binary files are identified, not decoded.
 */
binary: boolean, 
/**
 * Lines added, when they were counted.
 *
 * `None` for a binary file and for one too large to diff — there is no line
 * count to give, and inventing a zero would read as "nothing changed".
 */
additions: number | null, 
/**
 * Lines removed, on the same terms.
 */
deletions: number | null, };
