// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";
import type { Commit } from "./Commit";

/**
 * One commit that touched the file.
 */
export type FileCommit = { 
/**
 * The commit, in the same shape every other surface shows one.
 */
commit: Commit, 
/**
 * The name the file had at this commit.
 */
path: string, 
/**
 * What happened to it here.
 */
kind: ChangeKind, 
/**
 * The name it had before this commit renamed it, when this is where the
 * trace crossed a rename.
 */
renamedFrom: string | null, };
