// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileCommit } from "./FileCommit";
import type { FileCursor } from "./FileCursor";
import type { ScanStopped } from "./ScanStopped";

/**
 * The commits that touched one file.
 */
export type FileHistory = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "unknown" } | { "state": "ready", 
/**
 * The name the file has at the point it was asked about.
 */
path: string, 
/**
 * The commits that touched it, newest first.
 */
commits: Array<FileCommit>, 
/**
 * Where to continue, or `None` at the end of what is here.
 */
next: FileCursor | null, 
/**
 * How many commits were examined to produce this page.
 */
scanned: number, 
/**
 * Why it stopped.
 */
stopped: ScanStopped, 
/**
 * Whether this is a shallow clone, so the end is the end of the *copy*.
 */
shallow: boolean, };
