// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";
import type { Hunk } from "./Hunk";
import type { PatchTruncated } from "./PatchTruncated";

/**
 * What one file's change looks like.
 */
export type FileDiff = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "unknown" } | { "state": "binary", 
/**
 * Which path, and what happened to it.
 */
change: FileChange, 
/**
 * Its size before, where there was a before.
 */
oldBytes: number | null, 
/**
 * Its size after, where there is an after.
 */
newBytes: number | null, } | { "state": "tooLarge", 
/**
 * Which path, and what happened to it.
 */
change: FileChange, 
/**
 * How big the larger side is.
 */
bytes: number, 
/**
 * The ceiling that bit.
 */
limit: number, } | { "state": "ready", 
/**
 * Which path, and what happened to it.
 */
change: FileChange, 
/**
 * The patch.
 */
hunks: Array<Hunk>, 
/**
 * Whether it stops short, and where.
 */
truncated: PatchTruncated, };
