// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";
import type { FilterCursor } from "./FilterCursor";
import type { Head } from "./Head";
import type { ScanStopped } from "./ScanStopped";

/**
 * One page of a narrowed history.
 */
export type FilteredHistory = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "unknown" } | { "state": "ready", 
/**
 * Where `HEAD` is, for the surface's own header.
 */
head: Head, 
/**
 * The matches, newest first.
 */
commits: Array<Commit>, 
/**
 * Where to continue, or `None` when the search reached the end.
 */
next: FilterCursor | null, 
/**
 * How many commits were examined to produce this page.
 */
scanned: number, 
/**
 * Why it stopped.
 */
stopped: ScanStopped, 
/**
 * Whether this is a shallow clone.
 */
shallow: boolean, };
