// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { FileSubject } from "./FileSubject";

/**
 * Where to continue a filtered search.
 */
export type FilterCursor = { 
/**
 * The commit to resume examining at.
 */
from: CommitId, 
/**
 * The file, as of the resume point, when a file filter is on.
 *
 * Carried for the same reason a file trace carries it: a rename crossed
 * mid-search changes the name below it, and the new name is expressed as a
 * position in a change set rather than written down.
 */
file: FileSubject | null, };
