// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityReport } from "./CapabilityReport";

/**
 * Proof that the foundation is wired end to end.
 *
 * Every field here crosses one architectural boundary: the schema version comes
 * from `mira-db`, the counts through the repository and service traits, the
 * capabilities from `mira-platform`. If this command answers, the spine works.
 */
export type FoundationStatus = { 
/**
 * The application name.
 */
appName: string, 
/**
 * Its version, from `Cargo.toml`.
 */
appVersion: string, 
/**
 * The operating system, as a person would name it.
 */
platform: string, 
/**
 * The windowing system — the distinction a compile-time target cannot make.
 */
session: string, 
/**
 * Where the SQLite file lives.
 */
databasePath: string, 
/**
 * The applied schema version.
 */
schemaVersion: number, 
/**
 * How many projects exist. Zero until Slice 1 can add one.
 */
projectCount: number, 
/**
 * How many workspaces exist. Zero until 0.2.
 */
workspaceCount: number, 
/**
 * The chord Mira tried to register.
 */
shortcutChord: string, 
/**
 * Whether that registration succeeded here.
 */
shortcutRegistered: boolean, 
/**
 * Every capability and its honest status on this machine.
 */
capabilities: Array<CapabilityReport>, };
