// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";
import type { Head } from "./Head";
import type { Upstream } from "./Upstream";

/**
 * Everything Slice 1 reads about a project's Git state.
 */
export type GitOverview = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "ready", 
/**
 * Which branch, or which commit, is checked out.
 */
head: Head, 
/**
 * Whether the working tree has nothing to report.
 */
clean: boolean, 
/**
 * How many paths differ from HEAD, counting untracked files.
 */
changed: number, 
/**
 * HEAD's commit, absent only in a repository with no commits.
 */
lastCommit: Commit | null, 
/**
 * The tracked branch and the distance to it, when one is configured.
 */
upstream: Upstream | null, };
