// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefKind } from "./RefKind";

/**
 * One label on a row.
 *
 * Ordered by kind and then by name, so two reads of one repository label a row
 * the same way round.
 */
export type GitRef = { 
/**
 * What kind of reference it is. First, so ordering is by kind then name.
 */
kind: RefKind, 
/**
 * The short name, as Git would print it: `main`, `origin/main`, `v1.0`.
 */
name: string, };
