// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";
import type { CommitId } from "./CommitId";
import type { Edge } from "./Edge";
import type { GitRef } from "./GitRef";
import type { RowKind } from "./RowKind";

/**
 * One row of the graph: a commit, where it sits, and what it connects to.
 */
export type GraphRow = { 
/**
 * Everything the history list already showed. The same [`Commit`] type,
 * read by the same walk — there is no second history here.
 */
commit: Commit, 
/**
 * This commit's parents, in Git's order. The first is the mainline.
 */
parents: Array<CommitId>, 
/**
 * Which lane the node sits in, counting from the left.
 */
lane: number, 
/**
 * Root, ordinary, or merge.
 */
kind: RowKind, 
/**
 * Branch and tag labels that point at this commit.
 */
refs: Array<GitRef>, 
/**
 * The lines leaving this commit, one per parent.
 */
edges: Array<Edge>, 
/**
 * Lanes still occupied below this row, so the renderer can draw the
 * verticals that pass it by without recomputing the layout.
 */
continuing: Array<number>, };
