// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `HEAD` points at.
 */
export type Head = { "kind": "branch", 
/**
 * The short name, as `git branch` would print it.
 */
name: string, } | { "kind": "detached", 
/**
 * The abbreviated commit id.
 */
sha: string, } | { "kind": "unborn" };
