// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { FileSubject } from "./FileSubject";
import type { Term } from "./Term";

/**
 * What to narrow the history to.
 *
 * Composable: every field that is set has to match. All four unset is plain
 * history, which the default view reads through `history` instead — this is the
 * narrowed question, and it costs more to ask.
 */
export type HistoryFilter = { 
/**
 * Start the walk at this tip instead of `HEAD`.
 *
 * A commit id rather than a ref name, so there is no string here that could
 * ever be read as a revision expression. The interface picks a ref from
 * [`known_refs`] and sends the tip it was given.
 */
branch: CommitId | null, 
/**
 * Keep commits whose author's name contains this, ignoring case.
 */
author: Term | null, 
/**
 * Keep commits whose **subject line** contains this, ignoring case.
 *
 * Substring, not a pattern: no globbing, no regular expressions, no word
 * boundaries. The comparison is Unicode-lowercase on both sides, the query
 * is trimmed, and the body of the message is not searched.
 */
subject: Term | null, 
/**
 * Keep commits that touched this file.
 *
 * 5d's identity model, unchanged: a change set Mira produced and a position
 * in it. Renames are followed, exactly as they are in a file trace.
 */
file: FileSubject | null, };
