// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";

/**
 * One run of changed lines, with its surrounding context.
 */
export type Hunk = { 
/**
 * Git's own header, `@@ -a,b +c,d @@`, for a boundary a reader recognises.
 */
header: string, 
/**
 * The lines in it.
 */
lines: Array<DiffLine>, };
