// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long the machine is being asked to stay awake.
 *
 * A closed vocabulary, deliberately. The interface picks one of four words; it
 * cannot name a duration, so there is no number arriving from a webview that
 * something downstream has to bound.
 */
export type KeepAwakeSpan = "off" | "thirtyMinutes" | "oneHour" | "untilTurnedOff";
