// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeepAwakeSpan } from "./KeepAwakeSpan";

/**
 * Whether the machine is being kept awake, and on whose terms.
 *
 * A state the interface renders rather than an error it translates — including
 * `Unavailable`, which is what a platform with no public way to ask reports
 * (`platform-abstraction.md` §2 rule 4).
 */
export type KeepAwakeState = { "state": "off" } | { "state": "on", 
/**
 * Which choice produced this.
 */
span: KeepAwakeSpan, 
/**
 * When it ends by itself, Unix epoch seconds UTC. `None` means it does
 * not — it ends when the person says so, or when Mira quits.
 */
until: number | null, } | { "state": "unavailable", 
/**
 * Why not — true, specific, and not an apology.
 */
reason: string, 
/**
 * What to do instead, when there is something.
 */
fallback: string | null, };
