// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefTip } from "./RefTip";

/**
 * The references a filter may start from.
 */
export type KnownRefs = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "ready", 
/**
 * Branches, remotes and tags, in reading order.
 */
refs: Array<RefTip>, 
/**
 * Whether there were more than [`MAX_REFS`] to look at.
 */
truncated: boolean, };
