// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorCount } from "./AuthorCount";
import type { ScanStopped } from "./ScanStopped";

/**
 * The authors a filter may choose from.
 */
export type KnownAuthors = { "state": "notARepository" } | { "state": "unreadable", 
/**
 * What went wrong, in words a person can act on.
 */
detail: string, } | { "state": "ready", 
/**
 * Most frequent first, then alphabetical.
 */
authors: Array<AuthorCount>, 
/**
 * How many commits were examined.
 */
scanned: number, 
/**
 * Why the scan stopped.
 */
stopped: ScanStopped, };
