// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was started.
 */
export type Launched = { 
/**
 * The application Mira chose, or `None` when the desktop chose.
 */
application: string | null, };
