// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a patch.
 */
export type LineKind = "context" | "addition" | "deletion" | "note";
