// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One socket accepting connections.
 */
export type Listener = { 
/**
 * The port it is listening on.
 */
port: number, 
/**
 * The address it is bound to, as a person would type it.
 */
localAddress: string, 
/**
 * The process that owns it, where the operating system says.
 *
 * `None` happens: a socket owned by another user, or one whose process
 * exited between the scan and the read.
 */
pid: number | null, };
