// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectObservation } from "./ProjectObservation";
import type { ServiceObservation } from "./ServiceObservation";

/**
 * Everything observed, as one message to the interface.
 */
export type LiveSnapshot = { 
/**
 * One entry per project that has been observed at least once.
 */
projects: Array<ProjectObservation>, 
/**
 * The machine's listening ports.
 */
services: ServiceObservation, };
