// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";

/**
 * Anything that can go wrong, in a shape the interface can render.
 */
export type MiraError = { "kind": "notFound", 
/**
 * What was looked for, named the way the user named it.
 */
what: string, } | { "kind": "permissionDenied", 
/**
 * What was refused.
 */
what: string, 
/**
 * The action that would fix it, if there is one.
 */
hint: string, } | { "kind": "unsupported", 
/**
 * The capability that is off.
 */
capability: Capability, 
/**
 * Its user-facing reason string.
 */
reason: string, } | { "kind": "timeout", 
/**
 * What was being attempted.
 */
operation: string, 
/**
 * How long Mira waited.
 */
afterMs: number, } | { "kind": "external", 
/**
 * Which subsystem.
 */
source: string, 
/**
 * What it reported.
 */
detail: string, } | { "kind": "invalid", 
/**
 * Which field.
 */
field: string, 
/**
 * What is wrong with it.
 */
detail: string, };
