// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool that declares where a repository's packages live.
 *
 * Presence of the tool is a fact about the repository. Which packages exist is a
 * separate question, and not every tool answers it: Turborepo delegates to the
 * package manager, and Mira says so rather than guessing.
 */
export type MonorepoTool = "npmWorkspaces" | "pnpmWorkspaces" | "yarnWorkspaces" | "cargoWorkspace" | "turborepo" | "nx";
