// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One package boundary inside a project, from the monorepo detection.
 */
export type PackageBoundary = { 
/**
 * The package's own name.
 */
name: string, 
/**
 * Its path relative to the project root, with `/` separators.
 */
path: string, };
