// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One package inside a monorepo.
 */
export type Package = { 
/**
 * The name its own manifest gives it, or the directory name when it has none.
 *
 * Never invented: if neither exists, the directory is not reported at all.
 */
name: string, 
/**
 * Where it sits, relative to the monorepo root, with `/` separators.
 */
path: string, };
