// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a patch left out, if anything.
 */
export type PatchTruncated = { "state": "no" } | { "state": "lines", 
/**
 * How many lines are here.
 */
shown: number, 
/**
 * The ceiling that bit ([`MAX_LINES`]).
 */
limit: number, } | { "state": "bytes", 
/**
 * How many bytes are here.
 */
shown: number, 
/**
 * The ceiling that bit ([`MAX_BYTES`]).
 */
limit: number, };
