// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId";

/**
 * What happened when an action was performed.
 *
 * A sentence rather than a structure, because there is nothing for the
 * interface to *do* with the outcome except say it. A launch that started
 * nothing Mira can name still happened, and says so.
 */
export type Performed = { 
/**
 * Which action.
 */
id: ActionId, 
/**
 * What happened, in words.
 */
happened: string, };
