// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A TCP port Mira will talk about.
 *
 * Validated where it deserialises, so `0` and anything outside `u16` fail on
 * the wire rather than three layers down — and every other layer may assume a
 * `Port` is a port. This is the "validate port constraints centrally" rule with
 * one place to look.
 *
 * Note what this type is *not*: a way for the interface to name one. Nothing
 * the frontend sends carries a `Port`; a workspace names a service by an
 * ordinal in a list Mira offered, or by the row id Mira issued when it was
 * added. The type exists so that the value Mira reads from its own database is
 * checked before it is used (ADR-0020).
 */
export type Port = number;
