// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessFacts } from "./ProcessFacts";

/**
 * One listening socket, as the machine-wide view shows it.
 */
export type PortRow = { 
/**
 * Where this sits in the observation Mira took. What `live.open_service`
 * is given — never the port.
 */
at: number, 
/**
 * The port it is listening on.
 */
port: number, 
/**
 * The address it is bound to, as the platform reported it.
 */
address: string, 
/**
 * The process behind it, where the platform named one.
 *
 * Carries cpu, memory and uptime — and **no command line**, because argv
 * routinely holds credentials ([ADR-0022](../../../docs/adr/0022-process-detail.md)).
 */
process: ProcessFacts | null, };
