// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRow } from "./PortRow";
import type { ProjectId } from "./ProjectId";

/**
 * The listeners belonging to one project.
 */
export type PortGroup = { 
/**
 * Which project.
 */
projectId: ProjectId, 
/**
 * What it is called, so the group can be read without a second lookup.
 */
project: string, 
/**
 * Its listeners, in the order Mira observed them.
 */
rows: Array<PortRow>, };
