// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortGroup } from "./PortGroup";
import type { PortRow } from "./PortRow";

/**
 * Every listening socket on the machine, grouped as the IA describes.
 */
export type PortsView = { 
/**
 * One group per project that owns at least one listener, in project order.
 */
projects: Array<PortGroup>, 
/**
 * Listeners Mira could not place, with the reason on each row's own
 * attribution — kept apart rather than dropped, because on Windows this is
 * most of them and an empty view beside a running dev server would be a
 * worse lie than an uncertain one.
 */
unattributed: Array<PortRow>, 
/**
 * When the reading was taken; `None` means it has not been.
 */
observedAt: number | null, 
/**
 * What went wrong, if the last attempt failed.
 */
error: string | null, };
