// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What Mira knows about one running process.
 *
 * Everything except `pid` and `name` is optional, because every one of them is a
 * fact some platform declines to give. An absent field is reported as absent
 * rather than filled with a plausible value.
 */
export type ProcessFacts = { 
/**
 * The process identifier.
 */
pid: number, 
/**
 * The process name, as the operating system reports it.
 */
name: string, 
/**
 * The executable's path, where the platform allows reading it.
 */
executable: string | null, 
/**
 * The parent process identifier, where one is reported.
 */
parent: number | null, 
/**
 * The process's working directory.
 *
 * The single fact project attribution rests on. Windows does not expose it
 * for another process, which is why attribution there is Degraded and says
 * so instead of guessing (`platform-abstraction.md` §5).
 */
workingDirectory: string | null, 
/**
 * Share of one CPU, as a percentage, averaged over the interval between the
 * last two readings.
 *
 * `None` until there have been two. A share is a *rate*, and a rate needs
 * two samples — the first reading of a process has nothing to subtract, so
 * reporting `0.0` there would say "idle" about a process that might be
 * burning a core. Measured: a process spinning a full core reads `0.00%` on
 * a first sample and its true figure on the second
 * ([ADR-0022](../../../docs/adr/0022-process-detail.md)).
 *
 * Can exceed 100 on a multi-core machine: two busy threads read ~200.
 */
cpuShare: number | null, 
/**
 * Resident memory in bytes, where the platform reports it.
 */
memoryBytes: number | null, 
/**
 * How long the process has been running, in seconds.
 */
uptimeSeconds: number | null, };
