// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What Mira knows about one running process.
 *
 * Everything except `pid` and `name` is optional, because every one of them is a
 * fact some platform declines to give. An absent field is reported as absent
 * rather than filled with a plausible value.
 */
export type ProcessFacts = { 
/**
 * The process identifier.
 */
pid: number, 
/**
 * The process name, as the operating system reports it.
 */
name: string, 
/**
 * The executable's path, where the platform allows reading it.
 */
executable: string | null, 
/**
 * The parent process identifier, where one is reported.
 */
parent: number | null, 
/**
 * The process's working directory.
 *
 * The single fact project attribution rests on. Windows does not expose it
 * for another process, which is why attribution there is Degraded and says
 * so instead of guessing (`platform-abstraction.md` §5).
 */
workingDirectory: string | null, };
