// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";

/**
 * One project, as stored and as shown.
 *
 * Deliberately absent: whether the directory still exists. That is a runtime
 * state Mira observes on load, not a column that can go stale
 * (`data-model.md` §3.1).
 */
export type Project = { 
/**
 * Stable identity, independent of the directory's name or location.
 */
id: ProjectId, 
/**
 * What the user calls it. Inferred from the directory on add.
 */
name: string, 
/**
 * The canonical absolute path of the directory.
 */
rootPath: string, 
/**
 * Whether a Git worktree was found at or above the root.
 */
isGit: boolean, 
/**
 * The worktree root, when it differs from `root_path`.
 */
gitRoot: string | null, 
/**
 * Detected project types: `node`, `rust`, `go`, and so on.
 */
markers: Array<string>, 
/**
 * When the project was last opened, Unix epoch seconds UTC.
 */
lastOpenedAt: number | null, 
/**
 * When it was added.
 */
createdAt: number, 
/**
 * When any of its stored fields last changed.
 */
updatedAt: number, };
