// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a project — a directory on disk plus what Mira learned about it.
 */
export type ProjectId = number;
