// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitOverview } from "./GitOverview";
import type { ProjectId } from "./ProjectId";
import type { RepositoryLayout } from "./RepositoryLayout";

/**
 * What Mira last saw of one project.
 */
export type ProjectObservation = { 
/**
 * Which project.
 */
projectId: ProjectId, 
/**
 * Whether the directory is still on disk.
 */
directoryExists: boolean, 
/**
 * The repository state, absent when the directory is gone.
 */
git: GitOverview | null, 
/**
 * How the directory sits in the repository around it.
 */
layout: RepositoryLayout | null, 
/**
 * What went wrong, if the last attempt failed.
 *
 * Present alongside a previous `git`: the interface shows the older reading
 * *and* says it could not be refreshed, which is more useful than either
 * alone and is never mistaken for current.
 */
error: string | null, 
/**
 * When this was read, Unix epoch seconds UTC.
 */
observedAt: number, };
