// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitOverview } from "./GitOverview";
import type { Project } from "./Project";
import type { RepositoryLayout } from "./RepositoryLayout";

/**
 * A project and the Git state of its directory, as of right now.
 */
export type ProjectContext = { 
/**
 * The project as stored.
 */
project: Project, 
/**
 * Whether the directory is still on disk.
 *
 * A project whose folder was moved or deleted is *Missing*, never
 * auto-removed (`prd.md` FR-1.5).
 */
directoryExists: boolean, 
/**
 * The repository state, or `None` when there is no directory to read.
 */
git: GitOverview | null, 
/**
 * How the directory sits in the repository around it: on its own, as the
 * root of a monorepo, or as one package inside one.
 *
 * Computed here rather than stored: a workspace is edited by the people
 * working in it, and a cached package list is a list that goes wrong
 * silently (`data-model.md` §1 rule 2).
 */
layout: RepositoryLayout | null, };
