// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a reference is.
 *
 * Declared in the order labels are read, because that is the order `Ord` gives
 * and the order a row shows them in: where you are, then the branches, then what
 * a remote had, then tags.
 */
export type RefKind = "head" | "branch" | "remote" | "tag";
