// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { RefKind } from "./RefKind";

/**
 * A branch or tag the interface may filter by.
 */
export type RefTip = { 
/**
 * What kind of reference it is.
 */
kind: RefKind, 
/**
 * The short name, as Git would print it.
 */
name: string, 
/**
 * The commit it points at — which is what a filter actually carries.
 */
tip: CommitId, };
