// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonorepoTool } from "./MonorepoTool";
import type { Package } from "./Package";

/**
 * How the selected directory relates to the repository around it.
 */
export type RepositoryLayout = { "kind": "standalone" } | { "kind": "monorepoRoot", 
/**
 * Every tool found here. More than one is normal — pnpm and Turborepo
 * commonly sit together — and reporting only the first would be less true.
 */
tools: Array<MonorepoTool>, 
/**
 * The packages the tools declare and the filesystem confirms.
 */
packages: Array<Package>, } | { "kind": "package", 
/**
 * The tools found at the monorepo root.
 */
tools: Array<MonorepoTool>, 
/**
 * The absolute path of the monorepo root.
 */
monorepoRoot: string, 
/**
 * This package's path relative to that root, with `/` separators.
 */
packagePath: string, 
/**
 * This package's own name.
 */
packageName: string, };
