// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one commit is, in the shape a graph reads.
 */
export type RowKind = "root" | "normal" | "merge";
