// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a trace stopped where it did.
 */
export type ScanStopped = { "state": "no" } | { "state": "budget", 
/**
 * How many commits were examined.
 */
scanned: number, 
/**
 * The ceiling that bit ([`MAX_SCAN`]).
 */
limit: number, } | { "state": "renameLost", 
/**
 * The name the trace was following when it lost the thread.
 */
path: string, };
