// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Service } from "./Service";

/**
 * What Mira last saw of the machine's listening ports.
 */
export type ServiceObservation = { 
/**
 * The services found.
 */
services: Array<Service>, 
/**
 * What went wrong, if the last attempt failed.
 */
error: string | null, 
/**
 * When this was read; `None` means it has not been read yet.
 */
observedAt: number | null, };
