// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a watched service stands, right now.
 *
 * Five states rather than two, because "not running" and "Mira has not looked"
 * are different things to be told, and because a port that something *else*
 * has taken is neither running nor free. Collapsing them would mean an
 * interface that says "not running" when the truth is "cannot say" — the same
 * failure as reporting "no results" for a search that ran out of budget
 * (ADR-0018).
 */
export type ServiceState = { "kind": "running", 
/**
 * The address it is bound to, as the platform reported it.
 */
address: string, 
/**
 * What the owning process is called, where the platform says.
 */
process: string | null, 
/**
 * The owning process id, where the platform says.
 */
pid: number | null, } | { "kind": "notRunning" } | { "kind": "taken", 
/**
 * What the owning process is called, where the platform says.
 */
process: string | null, } | { "kind": "neverObserved" } | { "kind": "unreadable", 
/**
 * What the platform said, shown as-is.
 */
reason: string, };
