// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the project's observed services, as something a workspace could add.
 *
 * Carries the port so the list can be read — a person picks a service by
 * recognising `:5173 vite`, and hiding the number would make the chooser
 * useless. The port travels **outward** only: it is a reading being displayed,
 * and the way back is `at`, which is a position in this list rather than a
 * value the caller composed.
 */
export type ServiceOffer = { 
/**
 * Where this sits in the list. What [`workspaces_watch_service`] is given.
 */
at: number, 
/**
 * The port it is listening on.
 */
port: number, 
/**
 * The address it is bound to.
 */
address: string, 
/**
 * The owning process's name, where the platform reports one.
 */
process: string | null, 
/**
 * Whether this workspace already watches it.
 *
 * Sent rather than filtered out, so that `at` indexes a list that only
 * changes when the *machine* changes. A list that also reshuffled when a
 * selection changed would make every ordinal a race with the person using
 * it.
 */
watched: boolean, };
