// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribution } from "./Attribution";
import type { Listener } from "./Listener";
import type { ProcessFacts } from "./ProcessFacts";

/**
 * One listening socket, its process, and where it belongs.
 */
export type Service = { 
/**
 * The socket.
 */
listener: Listener, 
/**
 * The process that owns it, where the platform reports one.
 */
process: ProcessFacts | null, 
/**
 * Which project it belongs to, or why Mira will not say.
 */
attribution: Attribution, };
