// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which spelling of a commit id to copy.
 *
 * Two words, because there are two: the seven characters a person quotes in a
 * message, and the forty a tool wants. Nothing else can be asked for.
 */
export type ShaForm = "short" | "full";
