// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A short piece of text a filter compares against.
 *
 * Validated as it deserialises, like [`CommitId`]: bounded, single-line, not
 * empty. It is never handed to Git — it is compared in Rust against a field of a
 * commit already in memory — but the type is what makes that a property of the
 * boundary rather than of the code behind it.
 */
export type Term = string;
