// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a service could not be placed.
 */
export type Unattributed = "noOwningProcess" | "noWorkingDirectory" | "outsideEveryProject";
