// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The tracked branch, and how far HEAD is from it.
 */
export type Upstream = { 
/**
 * The upstream's short name, such as `origin/main`.
 */
name: string, 
/**
 * Commits on HEAD that the upstream does not have.
 */
ahead: number, 
/**
 * Commits on the upstream that HEAD does not have.
 */
behind: number, };
