// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Port } from "./Port";
import type { WorkspaceId } from "./WorkspaceId";
import type { WorkspaceServiceId } from "./WorkspaceServiceId";

/**
 * One service a workspace watches, as stored.
 *
 * Four fields, and the absences are the design. There is no label, no process
 * name, no address and no command — a stored row is a *port this workspace
 * cares about*, and everything else about it is observation that belongs to the
 * project and is read fresh (`data-model.md` §1 rule 2).
 *
 * The consequence is visible in the interface and is meant to be: a watched
 * service that has stopped is shown as its port and nothing more, because
 * everything Mira could have added would have been a memory of something that
 * is no longer true.
 */
export type WatchedService = { 
/**
 * Stable identity, issued by Mira when the service was added. This is what
 * the interface hands back to open or to stop watching — never a port.
 */
id: WorkspaceServiceId, 
/**
 * The workspace that watches it.
 */
workspaceId: WorkspaceId, 
/**
 * The port, as Mira read it from its own observation at the time.
 */
port: Port, 
/**
 * When it was added.
 */
addedAt: number, };
