// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId";
import type { ActionState } from "./ActionState";
import type { Effect } from "./Effect";

/**
 * One of a workspace's actions, as the interface receives it.
 */
export type WorkspaceAction = { 
/**
 * The catalogue identity. What the interface hands back to perform it.
 */
id: ActionId, 
/**
 * What to call it. Empty for an id with no row — there is nothing to call it.
 */
label: string, 
/**
 * What it will do, in a sentence.
 */
describes: string, 
/**
 * The icon beside the label.
 */
icon: string, 
/**
 * What it does, where Mira knows.
 */
effect: Effect | null, 
/**
 * Where it stands right now.
 */
state: ActionState, };
