// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppKind } from "./AppKind";
import type { ProjectId } from "./ProjectId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * One workspace, as stored and as shown.
 *
 * Deliberately absent: anything observed. There is no branch here, no port, no
 * process — those belong to the project and are read live, so that opening a
 * workspace shows the truth rather than a copy of it taken at some earlier time.
 */
export type Workspace = { 
/**
 * Stable identity.
 */
id: WorkspaceId, 
/**
 * The project it is a way of working on.
 */
projectId: ProjectId, 
/**
 * What the user calls it.
 */
name: string, 
/**
 * What it is for, if the user said. A good name usually says enough.
 */
description: string | null, 
/**
 * The kinds of application the user associated with it.
 */
applications: Array<AppKind>, 
/**
 * When it was last opened; `None` means never.
 */
lastOpenedAt: number | null, 
/**
 * When it was created.
 */
createdAt: number, 
/**
 * When any of its stored fields last changed.
 */
updatedAt: number, };
