// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one service a workspace watches.
 *
 * Issued by Mira when the service is added, and the *only* name the
 * interface has for it afterwards. Opening or forgetting a watched service
 * names this id, never the port behind it, so there is no request through
 * which a page could reach a port Mira did not already put on the row
 * (ADR-0020).
 */
export type WorkspaceServiceId = number;
