// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceState } from "./ServiceState";
import type { WatchedService } from "./WatchedService";

/**
 * A watched service and where it stands.
 */
export type WorkspaceService = { 
/**
 * What the workspace stated.
 */
watched: WatchedService, 
/**
 * What Mira observed.
 */
state: ServiceState, };
