// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a workspace — a named way of working on one project.
 */
export type WorkspaceId = number;
